#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'
feh --bg-scale ~/Pictures/tree.jpg &

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# THEMES
source $HOME/.config/herbstluftwm/theme.sh
hc keybind $Mod-Shift-z load "$(cat .hc/default.theme)"
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh

# SHORTCUTS
hc keybind $Mod-Shift-q quit # logout
hc keybind $Mod-Shift-r reload
hc keybind $Mod-c close
hc keybind $Mod-q close_or_remove
hc keybind $Mod-Return spawn lxterminal
hc keybind $Mod-w spawn firefox
hc keybind $Mod-d spawn dmenu_run
hc keybind $Mod-e spawn emacs

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Shift-s       split   vertical     0.5
hc keybind $Mod-s       split   horizontal   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.005
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# fast resizing frames
resizestep1=0.05
hc keybind $Mod-Control-Shift-h       resize left +$resizestep1
hc keybind $Mod-Control-Shift-j       resize down +$resizestep1
hc keybind $Mod-Control-Shift-k       resize up +$resizestep1
hc keybind $Mod-Control-Shift-l       resize right +$resizestep1
hc keybind $Mod-Control-Shift-Left    resize left +$resizestep1
hc keybind $Mod-Control-Shift-Down    resize down +$resizestep1
hc keybind $Mod-Control-Shift-Up      resize up +$resizestep1
hc keybind $Mod-Control-Shift-Right   resize right +$resizestep1


# resizing gap
hc keybind $Mod-g       cycle_value frame_gap 0 10 20 30 40 50 60 80
hc keybind $Mod-Shift-g cycle_value frame_gap 80 60 50 40 30 20 10 0 

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# media
hc keybind XF86AudioRaiseVolume spawn amixer sset Master 1%+
hc keybind XF86AudioLowerVolume spawn amixer sset Master 5%-

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 40

hc attr theme.active.color '#B26851'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#454545'
hc attr theme.active.outer_color '#BD4200'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

hc set default_frame_layout 3 # grid
hc set focus_follows_mouse 1
hc set focus_stealing_prevention 1
hc set frame_active_opacity 100
hc set frame_bg_transparent 1
hc set frame_normal_opacity 100
hc set gapless_grid 0
hc set mouse_recenter_gap 1
hc set pseudotile_center_threshold 0
hc set raise_on_click 1
hc set raise_on_focus 0
hc set raise_on_focus_temporarily 1
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 0
hc set snap_distance 20
hc set snap_gap 10
hc set swap_monitors_to_get_tag 0
hc set tree_style '╾│ ├└╼─┐'
hc set wmname 'Herbstluftwm'
hc set always_show_frame 0

# rules

hc unrule -F
hc rule class~'([Ff]irefox)' tag=1 # move all firefox to tag 1
hc rule class=emacs tag=2
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class='vlc' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
